/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_FxKqBYVfH",
        "userPoolWebClientId": "53h9gsbi7ic6sfgaeff3nai21a",
    },
    "aws_project_region": "us-east-2",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
